// Generated by https://quicktype.io

export interface TipoDocumento {
  id:                 string;
  tipo_documento:     string;
  estado:             string;
  fecha_creacion:     string;
  fecha_modificacion: string;
  fecha_eliminacion:  null;
  aud_login:          string;
}


